org: hungdinh
app: aws-rt-chat
service: aws-rt-chat
frameworkVersion: '3'

plugins:
    - serverless-esbuild
    - serverless-dynamodb-local
    - serverless-offline

custom:
    tableName: 'main-table-${sls:stage}'

provider:
    name: aws
    stage: dev
    runtime: nodejs14.x
    region: ap-southeast-1
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                      - dynamodb:BatchGetItem
                      - dynamodb:BatchWriteItem
                      - dynamodb:TransactGetItems
                      - dynamodb:TransactWriteItems
                  Resource:
                      - Fn::GetAtt: [MainTable, Arn]
                      - Fn::Join: [/, [Fn::GetAtt: [MainTable, Arn], 'index', 'gsi1']]
    environment:
        MAIN_TABLE: ${self:custom.tableName}

functions:
    getUsers:
        handler: './src/handlers/users/index.handler'
        events:
            - http:
                  path: /users
                  method: get
                  cors: true
    createUser:
        handler: './src/handlers/users/create.handler'
        events:
            - http:
                  path: /users
                  method: post
                  cors: true
    getUser:
        handler: './src/handlers/users/show.handler'
        events:
            - http:
                  path: /users/{id}
                  method: get
                  cors: true
resources:
    Resources:
        MainTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                    - AttributeName: pk
                      AttributeType: S
                    - AttributeName: gsi1pk
                      AttributeType: S
                    - AttributeName: gsi1sk
                      AttributeType: S
                KeySchema:
                    - AttributeName: pk
                      KeyType: HASH
                GlobalSecondaryIndexes:
                    - IndexName: gsi1
                      KeySchema:
                          - AttributeName: gsi1pk
                            KeyType: HASH
                          - AttributeName: gsi1sk
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
                BillingMode: PAY_PER_REQUEST
                TableName: ${self:custom.tableName}
