org: hungdinh
app: aws-rt-chat
service: aws-rt-chat
frameworkVersion: '3'

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    tableName: 'MAIN_TABLE'
    serverless-offline:
        ignoreJWTSignature: true

provider:
    name: aws
    stage: dev
    runtime: nodejs14.x
    region: ap-southeast-1
    logs:
        websocket: true
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                      - dynamodb:BatchGetItem
                      - dynamodb:BatchWriteItem
                      - dynamodb:TransactGetItems
                      - dynamodb:TransactWriteItems
                  Resource:
                      - Fn::GetAtt: [MainTable, Arn]
                      - Fn::Join: [/, [Fn::GetAtt: [MainTable, Arn], 'index', 'gsi1']]
    httpApi:
        payload: '2.0'
        cors:
            allowedHeaders:
                - Content-Type
                - Authorization
            allowedMethods:
                - GET
                - POST
                - OPTIONS
            allowedOrigins:
                - https://localhost:3003
        authorizers:
            customAuthorizer:
                type: request
                functionName: customAuthorizer
                identitySource: $request.header.Authorization
                resultTtlInSeconds: 300
                identityValidationExpression: 'Bearer .*'
    environment:
        MAIN_TABLE: ${self:custom.tableName}

functions:
    # Auth API
    login:
        handler: './src/handlers/auth/index.login'
        events:
            - httpApi:
                  path: /auth/login
                  method: post
    register:
        handler: './src/handlers/auth/index.register'
        events:
            - httpApi:
                  path: /auth/register
                  method: post

    # Authorizer API
    customAuthorizer:
        handler: './src/handlers/auth/index.authorizer'

    # USERS API
    getUsers:
        handler: './src/handlers/users/index.getUsers'
        events:
            - httpApi:
                  path: /users
                  method: get
                  authorizer:
                      name: customAuthorizer
    getUser:
        handler: './src/handlers/users/index.getUser'
        events:
            - httpApi:
                  path: /users/{id}
                  method: get
                  authorizer:
                      name: customAuthorizer

    # WEBSOCKET API
    wsOnConnect:
        handler: './src/handlers/ws/index.wsOnConnect'
        events:
            - websocket:
                  route: $connect
                  routeResponseSelectionExpression: $default
    wsOnDisconnect:
        handler: './src/handlers/ws/index.wsOnDisconnect'
        events:
            - websocket:
                  route: $disconnect
                  routeResponseSelectionExpression: $default
    wsDefault:
        handler: './src/handlers/ws/index.wsDefault'
        events:
            - websocket:
                  route: $default
                  routeResponseSelectionExpression: $default

    # CHAT WEBSOCKET API
    wsOnCreateRoom:
        handler: './src/handlers/ws/room/index.wsOnCreateRoom'
        events:
            - websocket:
                  route: createRoom
                  routeResponseSelectionExpression: $default
resources:
    Resources:
        MainTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                    - AttributeName: pk
                      AttributeType: S
                    - AttributeName: sk
                      AttributeType: S
                    - AttributeName: gsi1pk
                      AttributeType: S
                    - AttributeName: gsi1sk
                      AttributeType: S
                KeySchema:
                    - AttributeName: pk
                      KeyType: HASH
                    - AttributeName: sk
                      KeyType: RANGE
                GlobalSecondaryIndexes:
                    - IndexName: gsi1
                      KeySchema:
                          - AttributeName: gsi1pk
                            KeyType: HASH
                          - AttributeName: gsi1sk
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
                BillingMode: PAY_PER_REQUEST
                TableName: ${self:custom.tableName}
