export enum WSAction {
  ROOM_CREATED = 'ROOM_CREATED',
  ROOM_JOINED = 'ROOM_JOINED',
  MESSAGE_CREATED = 'MESSAGE_CREATED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  AUTHENTICATED = 'AUTHENTICATED',
}
